### ISSUE TITLE
Create a home page for the Raffles application

### ISSUE THREAD

**Issue by KarmaG-7** [KarmaG-7/raffle-frontend#1]
**Description:**

The home page should consist of a form to create a new raffle and a list of already available raffles. This feature will provide users with an intuitive interface to create and manage raffles.

**Steps to Test:**

- Open the Raffles application in a web browser.
- Navigate to the home page.
- Verify that the form to create a new raffle is displayed.
- Fill out the form with valid data and submit it.
- Verify that the new raffle is added to the list of available raffles.
- Try creating a new raffle with invalid data and verify that appropriate error messages are displayed.
- Verify that the list of available raffles is displayed below the form.
- Try deleting an existing raffle and verify that it is removed from the list.

**How to Build:**

- Design the user interface for the home page using HTML and CSS.
- Implement functionality to fetch existing raffles from the backend and display them on the page.
- Implement a form to allow users to create new raffles.
- Implement client-side validation for the form inputs.
- Implement functionality to submit the form data to the backend and add a new raffle.

**Comment by mikeboyle** [comment]
If it were me I would dig more into some aspects of the plan in `How to Build`.

- What state does this component need? 
- What should happen if client side validation fails?
- Loading state and error state?
- If the form submits successfully and a new raffle is added, how exactly are you going to add it to the list of available raffles below the form? I assume you want this to happen without the user having to refresh the page, but how will you implement that?

**Comment by mikeboyle** [comment]
Overall I think you can break the home page into smaller pieces, with a ticket for each one. For example:
1. Create the basic page / route / component
2. Fetch and display the list of raffles
3. Display the form and the happy path, including loading how to add the created raffle to the list of raffles
4. Form client-side validation
5. Handling server errors and error states
6. Loading states (how many loading states do you need?)
